Prepare unix domain server
NekoCdr-pets/tasknow pull request #12
Opened 2023-10-16 21:21 UTC by NekoCdr

Prepare unix domain server without business logic. It response with requested query method (if QM is correct).

2023-10-17 08:06 UTC, Endilll requested changes

2023-10-17 08:06 UTC, Endilll commented on src/defines.h
> +constexpr const char* DaemonSockPath{"/tmp/tasknowd.socket"};
Use `std::string_view`

2023-10-17 08:06 UTC, Endilll commented on src/serverd.cpp
> +    const char* sock_path
Use `std::string_view`

2023-10-17 08:06 UTC, Endilll commented on src/serverd.cpp
> +auto create_socket(int* server_sock) -> void
Why in-out param? You can simply return the created socket

2023-10-17 08:06 UTC, Endilll commented on src/serverd.cpp
> +auto serve(const char* sock_path, const int backlog_size) -> void
Why not use `std::string_view` here as well?

2023-10-17 08:06 UTC, Endilll commented on src/serverd.cpp
> +auto serve(const char* sock_path, const int backlog_size) -> void
Accepting values as `const` is not wrong, but certainly unconventional. In a not so often case when you really try to change value of in-parameter without using it later, compiler should catch it, and issue a warning.

2023-10-17 08:06 UTC, Endilll commented on src/serverd.cpp
> +        throw std::string_view{"Can't accept client"};
If you add `using namespace std::literals;` to your headers, you'd be able to write this much shorter: `throw "Can't accept client"sv;`

2023-10-17 08:06 UTC, Endilll commented on src/serverd.h
> +auto create_socket(int* server_sock) -> void;
Can you sprinkle empty lines in-between functions to increase readability?

2023-12-05 19:01 UTC, Endilll approved these changes
> *[Reviewable](https://reviewable.io/reviews/NekoCdr-pets/tasknow/12)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @NekoCdr)

___
*[`src/defines.h` line 25 at r2](https://reviewable.io/reviews/NekoCdr-pets/tasknow/12#-NkvLSuC7F3mcm3G3zi6:-NkvLSuD-56JZ4rb6gJK:b-aoe53d) ([raw file](https://github.com/NekoCdr-pets/tasknow/blob/0316560f6f189a1e33603d1f8c82e0c784a6cc9f/src/defines.h#L25)):*
> ```objc
> inline constexpr const int ErrorCode{-1};
> 
> constexpr const std::string_view DaemonSockPath{"/tmp/tasknowd.socket"};
> ```

You can use `""sv` here, and use `auto` instead of `std::string_view` then.


<!-- Sent from Reviewable.io -->

2023-12-05 19:05 UTC, Endilll reviewed
> *[Reviewable](https://reviewable.io/reviews/NekoCdr-pets/tasknow/12)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @NekoCdr)

___
*[`src/main.cpp` line 22 at r2](https://reviewable.io/reviews/NekoCdr-pets/tasknow/12#-NkvMaTv4wD8kYYKDuhM:-NkvMaTv4wD8kYYKDuhN:b-uzras6) ([raw file](https://github.com/NekoCdr-pets/tasknow/blob/0316560f6f189a1e33603d1f8c82e0c784a6cc9f/src/main.cpp#L22)):*
> ```cpp
>         tasknow::serverd::serve();
>     } catch (const std::string_view& error_msg) {
>         std::cout << error_msg << std::endl;
> ```

You can use `\n` instead of `std::endl`.


<!-- Sent from Reviewable.io -->

2023-12-05 19:24 UTC, NekoCdr reviewed
> *[Reviewable](https://reviewable.io/reviews/NekoCdr-pets/tasknow/12)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @Endilll)

___
*[`src/main.cpp` line 22 at r2](https://reviewable.io/reviews/NekoCdr-pets/tasknow/12#-NkvMaTv4wD8kYYKDuhM:-NkvQy4mBM-QMh-0kQaA:b-896fix) ([raw file](https://github.com/NekoCdr-pets/tasknow/blob/0316560f6f189a1e33603d1f8c82e0c784a6cc9f/src/main.cpp#L22)):*
<details><summary><i>Previously, Endilll (Vlad Serebrennikov) wrote…</i></summary><blockquote>

You can use `\n` instead of `std::endl`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-05 19:40 UTC, NekoCdr reviewed
> Dismissed @NekoCdr from a discussion.
> *[Reviewable](https://reviewable.io/reviews/NekoCdr-pets/tasknow/12)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Endilll)



<!-- Sent from Reviewable.io -->

2024-01-01 14:24 UTC, Endilll requested changes

2024-01-01 14:24 UTC, Endilll commented on src/serverd.h
> +    struct sockaddr_un* client_addr,
it's not a C code, so no need for elaborated type name (`struct`) here and everywhere

2024-01-01 14:24 UTC, Endilll commented on src/serverd.cpp
> +    int client_sock{};
no need to declare this outside of the loop

2024-01-01 14:24 UTC, Endilll commented on src/serverd.h
> +auto listen_socket(int* server_sock, const int backlog_size) -> void;
marking by-value parameters as `const` is not conventional

2024-01-01 14:24 UTC, Endilll commented on src/defines.h
> +constexpr const std::string_view DaemonSockPath{"/tmp/tasknowd.socket"};
why is this not `inline`?

2024-01-01 17:42 UTC, Endilll approved these changes

2024-01-01 17:44 UTC, merged